DROP TABLE IF EXISTS composer_song;
DROP TABLE IF EXISTS composers;
DROP TABLE IF EXISTS liturgies;
DROP TABLE IF EXISTS liturgy_part;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS songs_bk;
